# Generated by Django 3.2.3 on 2021-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20210711_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderproduct',
            name='product_photo_main',
            field=models.ImageField(blank=True, default='trends_photo/best_5.png', upload_to='order_product_image', verbose_name='order_product_image'),
        ),
    ]
